name: build
on:
  workflow_dispatch:
  push:
    branches: ['**']
jobs:
  latex-document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3.5.3

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Rename document
        run: mv main.pdf proposal-ta.pdf

      - name: Upload document as an artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: document
          path: proposal-ta.pdf
